name: Increment Version

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Increment the Version
      run: |
        npm run increment-version

    - name: Push Changes
      run: |
        git add ./package.json
        git add ./src/strings.ts
        git add ./spfx/config/package-solution.json
        git commit -m "Incremented the version of the solution." -a
        git push