name: Build & Package

on:
  project:
    types: [ closed ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Libraries
      run: |
        npm install
        cd spfx
        npm install
        cd ..

    - name: Build
      run: |
        npm run all

    - name: Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: |
          assets/config.json
          dist