name: Build & Package

on:
  project:
    types: [ closed ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        cd spfx
        npm install
        cd ..

    - name: Build
      run: |
        npm run all

    - name: Artifacts - JS Files
      uses: actions/upload-artifact@v2
      with:
        name: js
        path: dist/app-catalog-dashboard*.js

    - name: Artifacts - SPFx
      uses: actions/upload-artifact@v2
      with:
        name: spfx
        path: dist/app-catalog-mgr.sppkg

    - name: Artifacts - Config File
      uses: actions/upload-artifact@v2
      with:
        name: config
        path: assets/config.json